---
framework: jest
preRun:
     command:
        - yarn install
        - yarn run build
preMerge:
  pattern:
    - "test/test_selector.ts"
postMerge:
  pattern: 
    - "test/test_selector.ts"
postRun:
     command:
        - yarn --version
parallelism: 2
version: 1.0
